<a href="https://colab.research.google.com/github/letsgo247/Deep-Learning-Study/blob/master/Numpy_Archive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# np.random


In [5]:
# np.random.seed(0)
A = np.random.rand(3,5) #0부터 1사이의 균일 분포 (size)
B = np.random.randn(3,5)  #가우시안 표준 정규 분포(normal distribution)
C = np.random.randint(-10,10,(3,5)) #균일 분포의 정수 난수(integer) (최소값,최대값,(size))
print(A)
print(B)
print(C)

[[0.78908855 0.17758263 0.34648745 0.35994608 0.67187386]
 [0.89574113 0.45852146 0.38896888 0.58812815 0.04847539]
 [0.16438062 0.64617894 0.30822998 0.42438923 0.37441916]]
[[-0.77390389  0.03935142 -0.65206387  1.36858974  0.16089513]
 [-0.07769926  1.60955412  0.20606042  1.22752766  2.7644449 ]
 [ 0.06801386  0.75363547 -0.20676158 -1.34938024 -0.65674683]]
[[-6 -9 -2 -5 -1]
 [ 1  6 -6 -8 -4]
 [-5  5 -9  2 -4]]


# Array 에서 특정 조건 부합하는 데이터 골라내기

In [55]:
C = np.random.randint(-10,10,(3,5))
print(C)

C>0   #조건

[[-2 -6  1  3  2]
 [ 6 -9  8 -8 -5]
 [-1 -4 -8  9 -2]]


array([[False, False,  True,  True,  True],
       [ True, False,  True, False, False],
       [False, False, False,  True, False]])

In [54]:
print(C[C>0]) #해당 원소만 골라내기
print(C*(C>0))  #배열 유지한채 골라내기

[3 5 6 2 3 9 7]
[[3 5 0 0 6]
 [2 0 0 3 9]
 [0 7 0 0 0]]


# np.arange

In [3]:
np.arange(3)  #인수 하나면 stop

array([0, 1, 2])

In [11]:
np.arange(3,7)  #인수 두개면 start,stop

array([3, 4, 5, 6])

In [9]:
np.arange(3.0)  #dtype

array([0., 1., 2.])

In [12]:
np.arange(3,7,2)  #인수 세개면 interval

array([3, 5])

# np.argmax

In [64]:
a = np.random.randint(0,100,(5,3))
print(a)
b = np.random.randint(0,100,(5,3))

[[52 64 81]
 [42 14 80]
 [88 67 28]
 [53 95 94]
 [63 12  8]]


In [42]:
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

6
[2 4 2]
[2 1 0 2 1]


In [48]:
N, D = a.shape
maxidx = np.argmax(a,axis=1)
a[np.arange(N),maxidx]  #argmax로 찾은 최대값만 뽑아내기

array([25, 79, 96, 87, 93])

In [45]:
a[np.array([0,2,4])]  #특정 index 뽑아내기 1 (그냥  array가 아니라 np.array 쓰는게 포인트!)

array([[ 4,  4, 25],
       [96, 62, 94],
       [42, 93, 61]])

In [46]:
a[[0,2,4],:]  #특정 index 뽑아내기 2

array([[ 4,  4, 25],
       [96, 62, 94],
       [42, 93, 61]])

# max(=amax) vs maximum

In [68]:
A = np.random.randint(0,100,(5,3))
B = np.random.randint(0,100,(5,3))
print(A)
print(B)

[[93  5 19]
 [89 27 40]
 [73 72 90]
 [82 80 73]
 [57 74 90]]
[[ 7 41  5]
 [19 84 52]
 [75 33 35]
 [37 98 37]
 [86 45 28]]


In [70]:
A.max() #max: 하나의 배열에서 max 찾아냄

93

In [73]:
np.amax(B)  #amax = max

98

In [74]:
np.maximum(A,B) #maximum: 두개의 배열을 비교해서 더 큰 값 찾아냄

array([[93, 41, 19],
       [89, 84, 52],
       [75, 72, 90],
       [82, 98, 73],
       [86, 74, 90]])

# type vs dtype (& astype)

In [22]:
A = np.random.randint(1,4,(2,2))
print(A)

[[1 2]
 [2 3]]


In [23]:
type(A) #변수의 type

numpy.ndarray

In [24]:
A.dtype #변수가 사용하는 데이터의 dtype

dtype('int64')

In [57]:
A.astype(float) #데이터형 변환 'AsType'

array([[1., 1.],
       [2., 2.]])

# shape vs size (& flatten, reshape)

In [30]:
A = np.random.randint(1,4,(2,2))
print(A)

[[1 1]
 [2 2]]


In [31]:
A.shape #차원

(2, 2)

In [32]:
A.shape() #() 붙일 필요 없다! 문법 오류!

TypeError: ignored

In [0]:
A.size  #데이터의 개수

In [33]:
A.flatten() #Vectorize

array([1, 1, 2, 2])

In [34]:
A.reshape(4,1)

array([[1],
       [1],
       [2],
       [2]])

In [0]:
np.maximum()