<a href="https://colab.research.google.com/github/letsgo247/Deep-Learning-Study/blob/master/Numpy_Archive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# np.random


In [0]:
# np.random.seed(0)
A = np.random.rand(3,5) #0부터 1사이의 균일 분포 (size)
B = np.random.randn(3,5)  #가우시안 표준 정규 분포(normal distribution) (size)
C = np.random.randint(-10,10,(3,5)) #균일 분포의 정수 난수(integer) (최소값,최대값,(size))

print(A)
print(B)
print(C)

[[0.82090487 0.45963181 0.4414737  0.87510805 0.78822019]
 [0.77239542 0.141838   0.20285093 0.5585546  0.09142261]
 [0.88156108 0.78858421 0.277626   0.13542328 0.67662687]]
[[ 0.62501334 -1.11625026 -1.04990844  0.58170031  2.7924621 ]
 [-1.31535032 -0.67305919  0.45252564 -0.39764018  0.54348662]
 [-0.36691676 -1.90759531  1.0164531  -1.22251893  0.77775934]]
[[ 0 -9 -4  0  7]
 [-4  0 -6  5 -6]
 [-3 -7  2 -8  2]]


# zeros, ones, _like

In [0]:
a = np.zeros(5)
print(a)
b = np.ones((5,3))
print(b)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
c = np.zeros_like(b)  #_like for shape copy
print(c)
d = np.ones_like(a) #_like for shape copy
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]


# Array 에서 특정 조건 부합하는 데이터 골라내기

In [0]:
C = np.random.randint(-10,10,(3,5))
print(C)

C>0   #조건

[[-4  0  5  3 -3]
 [-1 -7  1 -4 -6]
 [-2 -7  4 -2 -5]]


array([[False, False,  True,  True, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False]])

In [0]:
print(C[C>0]) #해당 원소만 골라내기
print(C*(C>0))  #배열 유지한채 골라내기

[5 3 1 4]
[[0 0 5 3 0]
 [0 0 1 0 0]
 [0 0 4 0 0]]


# np.arange

In [0]:
np.arange(3)  #인수 하나면 stop

array([0, 1, 2])

In [0]:
np.arange(3,7)  #인수 두개면 start,stop

array([3, 4, 5, 6])

In [0]:
np.arange(3.0)  #dtype

array([0., 1., 2.])

In [0]:
np.arange(3,7,2)  #인수 세개면 interval

array([3, 5])

# np.argmax

In [0]:
a = np.random.randint(0,100,(5,3))
print(a)
b = np.random.randint(0,100,(5,3))

[[48 70 29]
 [54 40 32]
 [46 91 99]
 [87 34 86]
 [75 55 56]]


In [0]:
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

8
[3 2 2]
[1 0 2 0 0]


In [0]:
N, D = a.shape
maxidx = np.argmax(a,axis=1)
a[np.arange(N),maxidx]  #argmax로 찾은 최대값만 뽑아내기

array([70, 54, 99, 87, 75])

In [0]:
a[np.array([0,2,4])]  #특정 index 뽑아내기 1 (그냥  array가 아니라 np.array 쓰는게 포인트!)

array([[48, 70, 29],
       [46, 91, 99],
       [75, 55, 56]])

In [0]:
a[[0,2,4],:]  #특정 index 뽑아내기 2

array([[48, 70, 29],
       [46, 91, 99],
       [75, 55, 56]])

# max(=amax) vs maximum

In [0]:
A = np.random.randint(0,100,(5,3))
B = np.random.randint(0,100,(5,3))
print(A)
print(B)

[[93 88 37]
 [72 89 62]
 [22 98 20]
 [95  8 90]
 [21 66 57]]
[[38 86 22]
 [57 21 62]
 [86 51 42]
 [18 19 18]
 [19 72 49]]


In [0]:
A.max() #max: 하나의 배열에서 max 찾아냄

98

In [0]:
np.amax(B)  #amax = max

86

In [0]:
np.maximum(A,B) #maximum: 두개의 배열을 비교해서 더 큰 값 찾아냄

array([[93, 88, 37],
       [72, 89, 62],
       [86, 98, 42],
       [95, 19, 90],
       [21, 72, 57]])

# type vs dtype (& astype)

In [0]:
A = np.random.randint(1,4,(2,2))
print(A)

[[3 3]
 [3 2]]


In [0]:
type(A) #변수의 type

numpy.ndarray

In [0]:
A.dtype #변수가 사용하는 데이터의 dtype

dtype('int64')

In [0]:
A.astype(float) #데이터형 변환 'AsType'

array([[3., 3.],
       [3., 2.]])

# shape vs size (& flatten, reshape)

In [0]:
A = np.random.randint(1,4,(2,2))
print(A)

[[2 2]
 [2 1]]


In [0]:
A.shape #차원의 형상

(2, 2)

In [0]:
A.shape() #() 붙일 필요 없다! 문법 오류!

TypeError: ignored

In [0]:
A.ndim  #차원 개수

In [0]:
A.size  #데이터의 개수

In [0]:
A.flatten() #Vectorize

In [0]:
A.reshape(4,1)

In [0]:
np.maximum()