<a href="https://colab.research.google.com/github/letsgo247/Deep-Learning-Study/blob/master/Numpy_Archive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

np.random


In [5]:
# np.random.seed(0)
A = np.random.rand(3,5) #0부터 1사이의 균일 분포 (size)
B = np.random.randn(3,5)  #가우시안 표준 정규 분포(normal distribution)
C = np.random.randint(-10,10,(3,5)) #균일 분포의 정수 난수(integer) (최소값,최대값,(size))
print(A)
print(B)
print(C)

[[0.78908855 0.17758263 0.34648745 0.35994608 0.67187386]
 [0.89574113 0.45852146 0.38896888 0.58812815 0.04847539]
 [0.16438062 0.64617894 0.30822998 0.42438923 0.37441916]]
[[-0.77390389  0.03935142 -0.65206387  1.36858974  0.16089513]
 [-0.07769926  1.60955412  0.20606042  1.22752766  2.7644449 ]
 [ 0.06801386  0.75363547 -0.20676158 -1.34938024 -0.65674683]]
[[-6 -9 -2 -5 -1]
 [ 1  6 -6 -8 -4]
 [-5  5 -9  2 -4]]


Array 에서 특정 조건 부합하는 데이터 골라내기

In [6]:
C = np.random.randint(-10,10,(3,5))
print(C)

D = C>0   #조건

print(D*C)

[[  4   9   9   0   4]
 [ -9   4   0 -10   1]
 [  7   0  -4   9   0]]
[[4 9 9 0 4]
 [0 4 0 0 1]
 [7 0 0 9 0]]


np.argmax

In [7]:
a = np.arange(6).reshape(2,3) + 10
print(a)

[[10 11 12]
 [13 14 15]]


In [8]:
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

5
[1 1 1]
[2 2]


np.arange

In [3]:
np.arange(3)  #인수 하나면 stop

array([0, 1, 2])

In [11]:
np.arange(3,7)  #인수 두개면 start,stop

array([3, 4, 5, 6])

In [9]:
np.arange(3.0)  #dtype

array([0., 1., 2.])

In [12]:
np.arange(3,7,2)  #인수 세개면 interval

array([3, 5])