<a href="https://colab.research.google.com/github/letsgo247/Deep-Learning-Study/blob/master/Numpy_Archive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# np.random


In [ ]:
# np.random.seed(0)
A = np.random.rand(3,5) #0부터 1사이의 균일 분포 (size)
B = np.random.randn(3,5)  #가우시안 표준 정규 분포(normal distribution; 평균0, 표준편차1) (size)
C = np.random.randint(-10,10,(3,5)) #균일 분포의 정수 난수(integer) ((최소값, default=0),최대값,(size))

print(A)
print(B)
print(C)

[[0.99682061 0.72156386 0.27289128 0.49266388 0.75952724]
 [0.62497272 0.01274671 0.53751484 0.13796043 0.63978534]
 [0.21387595 0.38617452 0.68799457 0.84252086 0.21522958]]
[[-0.67688634 -2.05893387 -0.30032544 -2.15821572  0.6926934 ]
 [-0.78203419 -0.01346537  0.85954915 -1.62546525  0.35024905]
 [ 0.11380367 -1.39839978 -0.84733542  0.10210685  0.65676886]]
[[  6  -3   1   9  -2]
 [-10   2  -7   2   0]
 [-10  -6 -10   8   8]]


In [ ]:
x = np.random.randn(3,5)
print(x)

y = np.random.rand(*x.shape)
print(y)

[[-0.92756329  0.40594409 -2.17666589 -0.73478967  1.17989403]
 [ 1.44345013  2.02720479 -1.49917351  2.82492264  1.16633474]
 [-0.57191342  0.67301446  1.86852544  0.45947469  0.31364166]]
[[0.52100984 0.94781824 0.47554829 0.63942976 0.45212528]
 [0.92990177 0.81984119 0.90767376 0.27008127 0.3505262 ]
 [0.9813677  0.9636095  0.82574026 0.30215038 0.08376641]]


# zeros, ones, _like

In [ ]:
a = np.zeros(5)
print(a)
b = np.ones((5,3))
print(b)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
c = np.zeros_like(b)  #_like for shape copy
print(c)
d = np.ones_like(a) #_like for shape copy
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]


#sum

In [ ]:
a = np.array([[0, 0, 0],
              [0, 1, 0],
              [0, 2, 0],
              [1, 0, 0],
              [1, 1, 0]])

print(np.sum(a, axis=1, keepdims=True))   #keepdims: 기존의 dimension(not shape)를 유지
print(np.sum(a, axis=1, keepdims=False))
print(np.sum(a, axis=0, keepdims=True))
print(np.sum(a, axis=0, keepdims=False))

[[0]
 [1]
 [2]
 [1]
 [2]]
[0 1 2 1 2]
[[2 4 0]]
[2 4 0]


#prod (=product, 내적)

In [4]:
c  = np.array([[1, 2],
            [3, 4]])

print(np.prod(c))
print(np.prod(c, axis=0))
print(np.prod(c, axis=1))

24
[3 8]
[ 2 12]


# Array 에서 특정 조건 부합하는 데이터 골라내기

In [ ]:
C = np.random.randint(-10,10,(3,5))
print(C)

C>0   #조건

[[  1  -3   9  -6  -5]
 [ -1   8  -9   1   0]
 [-10  -9  -2   1 -10]]


array([[ True, False,  True, False, False],
       [False,  True, False,  True, False],
       [False, False, False,  True, False]])

In [ ]:
print(C[C>0]) #해당 원소만 골라내기
print(C*(C>0))  #배열 유지한채 골라내기

[1 9 8 1 1]
[[1 0 9 0 0]
 [0 8 0 1 0]
 [0 0 0 1 0]]


In [ ]:
#길지만 조금 더 직관적인 방법
D = np.random.randint(-10,10,(3,5))
print(D)

mask = (D<=0)
print(mask)

D[mask] = 0
print(D)

[[ -1  -4  -4   5   6]
 [ -3   3  -1 -10   6]
 [  4  -5  -1   2  -9]]
[[ True  True  True False False]
 [ True False  True  True False]
 [False  True  True False  True]]
[[0 0 0 5 6]
 [0 3 0 0 6]
 [4 0 0 2 0]]


# np.arange

In [ ]:
np.arange(3)  #인수 하나면 stop

array([0, 1, 2])

In [ ]:
np.arange(3,7)  #인수 두개면 start,stop

array([3, 4, 5, 6])

In [ ]:
np.arange(3.0)  #dtype

array([0., 1., 2.])

In [ ]:

np.arange(3,7,2)  #인수 세개면 interval

array([3, 5])

#np.linspace (='Linearly spaced' vectors)

In [ ]:
d = np.linspace(0, 10, 5)    #start ~ end 사이의 값을 num 개수만큼 생성하여 numpy array로 반환합니다.
c = np.linspace(0, 10, num=5, endpoint=False, retstep=False)    # endpoint가 True일 경우 end의 값이 마지막 값이 되며, False일 경우 end의 값을 마지막 값으로 사용하지 않습니다.
a = np.linspace(0, 10, num=5, endpoint=True, retstep=True)    # retstep이 True일 경우 값들의 간격을 배열에 포함합니다. numpy.arange()의 step과 동일한 의미를 지닙니다.
             #default :   50           True          False
print(d)
print(c)
print(a)

type(d)

[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)


numpy.ndarray

# np.argmax

In [ ]:
a = np.random.randint(0,100,(5,3))
print(a)
b = np.random.randint(0,100,(5,3))

[[23 40 80]
 [92 46  7]
 [90 27 70]
 [69 52 89]
 [86 66 64]]


In [ ]:
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))   #'axis'는 진짜 그 '축'의 방향을 생각하면 맞다. '데이터'의 방향을 생각하면 헷갈린다.

3
[1 4 3]
[2 0 0 2 0]


In [ ]:
N, D = a.shape
maxidx = np.argmax(a,axis=1)
a[np.arange(N),maxidx]  #argmax로 찾은 최대값만 뽑아내기

array([80, 92, 90, 89, 86])

In [ ]:
a[np.array([0,2,4])]  #특정 index 뽑아내기 1 (그냥  array가 아니라 np.array 쓰는게 포인트!)

array([[23, 40, 80],
       [90, 27, 70],
       [86, 66, 64]])

In [ ]:
a[[0,2,4],:]  #특정 index 뽑아내기 2

array([[23, 40, 80],
       [90, 27, 70],
       [86, 66, 64]])

# max(=amax) vs maximum

In [ ]:
A = np.random.randint(0,100,(5,3))
B = np.random.randint(0,100,(5,3))
print(A)
print(B)

[[78 65 65]
 [30 61 89]
 [76 52 77]
 [ 9 44 48]
 [34 51 40]]
[[96 60 85]
 [ 3 68 77]
 [ 9 73 41]
 [42 92 61]
 [48 56 75]]


In [ ]:
A.max() #max: 하나의 배열에서 max 찾아냄

89

In [ ]:
np.amax(B)  #amax = max

96

In [ ]:
np.maximum(A,B) #maximum: 두개의 배열을 비교해서 더 큰 값 찾아냄

array([[96, 65, 85],
       [30, 68, 89],
       [76, 73, 77],
       [42, 92, 61],
       [48, 56, 75]])

# type vs dtype (& astype)

In [ ]:
A = np.random.randint(1,4,(2,2))
print(A)

[[3 1]
 [1 2]]


In [ ]:
type(A) #변수의 type

numpy.ndarray

In [28]:
B = [[1,2],[3,4]]
print(type(B))
C = np.asarray(B)   #입력된 데이터를 numpy.ndarray() 형식으로 만들어 줌
print(type(C))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
A.dtype #변수가 사용하는 데이터의 dtype

dtype('int64')

In [ ]:
A.astype(float) #데이터형 변환 'AsType'

array([[3., 1.],
       [1., 2.]])

# shape vs size (& flatten, reshape)

In [ ]:
A = np.random.randint(1,4,(2,2))
print(A)

[[2 1]
 [1 3]]


In [ ]:
A.shape #차원의 형상

# A.shape() #() 붙일 필요 없다! 문법 오류!

(2, 2)

In [ ]:
A.ndim  #차원 개수

2

In [ ]:
A.size  #데이터의 개수

4

In [ ]:
A.flatten() #Vectorize

array([2, 1, 1, 3])

In [ ]:
A.ravel() #flatten과 같은 기능. 'ravel'='얽힌 것을 풀다'

array([2, 1, 1, 3])

In [ ]:
A.reshape(2,2,-1)  #reshape()의 '-1'이 의미하는 바는, 변경된 배열의 '-1' 위치의 차원은 '원래 배열의 길이와 남은 차원으로 부터 추정 된다'는 뜻

array([[[2],
        [1]],

       [[1],
        [3]]])

# linalg

In [ ]:
np.linalg.norm(A) #벡터의 norm(=크기, 스칼라 값) 계산

3.872983346207417

#배열 붙이기 (r_, c_, hstack, vstack, concatenate)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
#두 배열을 왼쪽에서 오른쪽으로 붙이기 

np.r_[a, b]
np.hstack([a, b])
np.concatenate((a, b), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#두 배열을 위에서 아래로 붙이기

np.r_[[a], [b]]
np.vstack([a, b])
# np.concatenate((c, d), axis = 1) # for 2D ~ array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#두 개의 1차원 배열을 칼럼으로 세로로 붙여서 2차원 배열 만들기

np.c_[a, b]
np.column_stack([a, b])
# np.concatenate((c.T, d.T), axis = 1) # for 2D~ array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
params = {}
c = 1
params['a'+str(c)] = (1,2)
print(params)

{'a1': (1, 2)}


In [21]:
baram = {}
baram['a'] = (1,2)
baram['b'] = (3,4)
print(baram['a'])

(1, 2)


#Test Board

In [45]:
a = len((1,2))

for i in range(a):
  print(i)

0
1
