<a href="https://colab.research.google.com/github/letsgo247/Deep-Learning-Study/blob/master/Python_Archive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *(=Asterisk) 사용법


1. 가변인자 (Variadic Parameters)를 사용하고자 할 때

In [1]:
# positional arguments만 받을 때

def save_ranking(*args):
    print(args)
save_ranking('ming', 'alice', 'tom', 'wilson', 'roy')

('ming', 'alice', 'tom', 'wilson', 'roy')


In [2]:
# keyword arguments만 받을 때
def save_ranking(**kwargs):
    print(kwargs)
save_ranking(first='ming', second='alice', fourth='wilson', third='tom', fifth='roy')

{'first': 'ming', 'second': 'alice', 'fourth': 'wilson', 'third': 'tom', 'fifth': 'roy'}


In [3]:
# positional arguments와 keyword arguments를 모두 받을 때

def save_ranking(*args, **kwargs):
    print(args)
    print(kwargs)
save_ranking('ming', 'alice', 'tom', fourth='wilson', fifth='roy')

('ming', 'alice', 'tom')
{'fourth': 'wilson', 'fifth': 'roy'}


2. 컨테이너 타입의 데이터를 Unpacking 할 때

In [9]:
import numpy as np

x = np.random.randn(3,5)
print(x)

y = np.random.rand(*x.shape)    #된다
print(y)

z = np.random.rand(x.shape)   #안된다 ㄷㄷ
print(z)

[[-1.28917103 -0.37797807 -1.7409648  -1.15542163 -1.36217025]
 [ 0.60673275  0.19950394 -0.93684013  0.80860127 -0.77280919]
 [ 0.41514368 -0.48968947 -0.54992151 -0.73383539 -1.40389326]]
[[0.52822951 0.10742969 0.3771943  0.74454422 0.62772464]
 [0.9890924  0.00383514 0.19899767 0.99734404 0.85280451]
 [0.99781309 0.7270876  0.89925422 0.6597931  0.49146648]]
[[0.32059242 0.48752985 0.61719596 0.14672891 0.46710691]
 [0.40003845 0.53224519 0.41174279 0.25880204 0.91574115]
 [0.72980436 0.26323487 0.7468455  0.52455647 0.90427848]]
