<a href="https://colab.research.google.com/github/letsgo247/Deep-Learning-Study/blob/master/Python_Archive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *(=Asterisk) 사용법


1. 가변인자 (Variadic Parameters)를 사용하고자 할 때

In [ ]:
# positional arguments만 받을 때

def save_ranking(*args):
    print(args)
save_ranking('ming', 'alice', 'tom', 'wilson', 'roy')

('ming', 'alice', 'tom', 'wilson', 'roy')


In [ ]:
# keyword arguments만 받을 때
def save_ranking(**kwargs):
    print(kwargs)
save_ranking(first='ming', second='alice', fourth='wilson', third='tom', fifth='roy')

{'first': 'ming', 'second': 'alice', 'fourth': 'wilson', 'third': 'tom', 'fifth': 'roy'}


In [ ]:
# positional arguments와 keyword arguments를 모두 받을 때

def save_ranking(*args, **kwargs):
    print(args)
    print(kwargs)
save_ranking('ming', 'alice', 'tom', fourth='wilson', fifth='roy')

('ming', 'alice', 'tom')
{'fourth': 'wilson', 'fifth': 'roy'}


2. 컨테이너 타입의 데이터를 Unpacking 할 때

In [ ]:
import numpy as np

x = np.random.randn(3,5)
print('x = ',x)

y = np.random.rand(*x.shape)    #된다
print('y = ',y)

z = np.random.rand(x.shape)   #안된다 ㄷㄷ
print(z)

x =  [[ 0.09853065 -0.27099711  1.05836033 -0.55462487 -2.16804431]
 [-0.72320301  0.58314736 -0.08569674 -1.03939068  0.37691913]
 [-0.73940802 -0.05942183 -0.45182276  0.16928696  0.85557402]]
y =  [[0.80954516 0.41296193 0.72398347 0.864546   0.46374481]
 [0.23231487 0.79604905 0.8166334  0.54107966 0.85662205]
 [0.20120774 0.40967766 0.81006001 0.79722221 0.05733555]]


TypeError: ignored

#dict 관련

dict.setdefault('key', value): dict에 해당 key가 없을 때 key 만들면서 기본값 넣어주는 함수

In [ ]:
s= ['a', 'b', 'c', 'b', 'a', 'b', 'c']
d= {}

for k in s:
  d.setdefault(k,0) #d 에 k 가 있는지 찾아서, 없으면 k:0 쌍을 만듦!
  d[k]+=1

list(d.items())

[('a', 2), ('b', 3), ('c', 2)]

dict.get('key', value): 'key'를 호출하는데, 만약 'key'가 없을 경우 value 를 호출

In [ ]:
eps = d.get("eps", 1e-5)
print(eps)

1e-05


#Test Board